pretrained_base_model_path: './pretrained_weights/sd-image-variations-diffusers'
pretrained_vae_path: './pretrained_weights/sd-vae-ft-mse'
image_encoder_path: './pretrained_weights/image_encoder'



denoising_unet_path: "./pretrained_weights/MusePose/denoising_unet.pth"
reference_unet_path: "./pretrained_weights/MusePose/reference_unet.pth"
pose_guider_path: "./pretrained_weights/MusePose/pose_guider.pth"
motion_module_path: "./pretrained_weights/MusePose/motion_module.pth"



inference_config: "./configs/inference_v2.yaml"
weight_dtype: 'fp16'



test_cases:
  "E:/CASIA_Gait_Dataset/DatasetB-frames-test-1280960-detect-50-new-max1/076/nm-01/126/ref.png":
    - "E:/CASIA_Gait_Dataset/DatasetB-frames-test-1280960-detect-50-new-video-pose/075/nm-01/126/075-nm-01-126.mp4"

